// Product packages should import standard App capabilities through this module.
// Keeping this surface explicit localizes compatibility work when App internals evolve.
export { PromptInput } from "./components/prompt-input"
export { buildRequestParts } from "./components/prompt-input/build-request-parts"
export { notifySessionTabsRemoved } from "./components/titlebar-session-events"
export { directoryKey } from "./context/global-sync/utils"
export { useLayout } from "./context/layout"
export { useLocal } from "./context/local"
export { usePlatform } from "./context/platform"
export { useProductSession, type ProductSessionAdapter } from "./context/product"
export { DEFAULT_PROMPT, usePrompt, type ImageAttachmentPart, type Prompt } from "./context/prompt"
export { useSDK } from "./context/sdk"
export { useServer } from "./context/server"
export { useServerSDK } from "./context/server-sdk"
export { useServerSync } from "./context/server-sync"
export { useSettings } from "./context/settings"
export { useSync } from "./context/sync"
export { useTabs } from "./context/tabs"
export { createPromptInputController } from "./pages/session/composer"
export { blobDataUrl } from "./utils/draft-store"
export { Identifier } from "./utils/id"
export { Persist, persisted, removePersisted } from "./utils/persist"
export { authTokenFromCredentials } from "./utils/server"
export { showToast } from "./utils/toast"
export { uuid } from "./utils/uuid"
