export const AI_SCIENCE_DAG_LEVELS = [
  ["ai-for-science-team/as-intent-router"],
  ["ai-for-science-team/as-asset-auditor", "ai-for-science-team/as-feasibility-advisor"],
  ["ai-for-science-team/as-research-planner"],
  ["ai-for-science-team/as-literature-strategist", "ai-for-science-team/as-methodology-designer"],
  ["ai-for-science-team/as-literature-researcher", "ai-for-science-team/as-experiment-designer"],
  ["ai-for-science-team/as-paper-evidence-analyst", "ai-for-science-team/as-code-data-engineer"],
  ["ai-for-science-team/as-research-synthesizer", "ai-for-science-team/as-experiment-operator"],
  [
    "ai-for-science-team/as-experiment-diagnostician",
    "ai-for-science-team/as-result-analyst",
    "ai-for-science-team/as-outline-architect",
  ],
  ["ai-for-science-team/as-evidence-writer"],
  ["ai-for-science-team/as-figure-citation-editor"],
  ["ai-for-science-team/as-independent-reviewer"],
  ["ai-for-science-team/as-quality-citation-auditor"],
  ["ai-for-science-team/as-research-package-curator"],
] as const

export const AI_SCIENCE_DAG_EDGES = [
  ["ai-for-science-team/as-intent-router", "ai-for-science-team/as-asset-auditor"],
  ["ai-for-science-team/as-intent-router", "ai-for-science-team/as-feasibility-advisor"],
  ["ai-for-science-team/as-intent-router", "ai-for-science-team/as-research-planner"],
  ["ai-for-science-team/as-asset-auditor", "ai-for-science-team/as-research-planner"],
  ["ai-for-science-team/as-feasibility-advisor", "ai-for-science-team/as-research-planner"],
  ["ai-for-science-team/as-research-planner", "ai-for-science-team/as-literature-strategist"],
  ["ai-for-science-team/as-research-planner", "ai-for-science-team/as-methodology-designer"],
  ["ai-for-science-team/as-literature-strategist", "ai-for-science-team/as-literature-researcher"],
  ["ai-for-science-team/as-literature-researcher", "ai-for-science-team/as-paper-evidence-analyst"],
  ["ai-for-science-team/as-paper-evidence-analyst", "ai-for-science-team/as-research-synthesizer"],
  ["ai-for-science-team/as-methodology-designer", "ai-for-science-team/as-experiment-designer"],
  ["ai-for-science-team/as-experiment-designer", "ai-for-science-team/as-code-data-engineer"],
  ["ai-for-science-team/as-code-data-engineer", "ai-for-science-team/as-experiment-operator"],
  ["ai-for-science-team/as-experiment-operator", "ai-for-science-team/as-experiment-diagnostician"],
  ["ai-for-science-team/as-experiment-operator", "ai-for-science-team/as-result-analyst"],
  ["ai-for-science-team/as-research-synthesizer", "ai-for-science-team/as-outline-architect"],
  ["ai-for-science-team/as-result-analyst", "ai-for-science-team/as-outline-architect"],
  ["ai-for-science-team/as-outline-architect", "ai-for-science-team/as-evidence-writer"],
  ["ai-for-science-team/as-evidence-writer", "ai-for-science-team/as-figure-citation-editor"],
  ["ai-for-science-team/as-figure-citation-editor", "ai-for-science-team/as-independent-reviewer"],
  ["ai-for-science-team/as-independent-reviewer", "ai-for-science-team/as-quality-citation-auditor"],
  ["ai-for-science-team/as-quality-citation-auditor", "ai-for-science-team/as-research-package-curator"],
] as const
